[build]
    publish = "exampleSite/public"
    command = "npm run build:example"
[build.environment]
    DART_SASS_VERSION = "1.83.1"
    HUGO_VERSION = "0.140.2"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"
    NODE_VERSION = "22.12.0"
    NPM_VERSION = "10.9.0"